language: go
go:
- 1.x
sudo: false
before_install:
  - go get github.com/mattn/goveralls
before_script:
  - go vet ./...
  - $GOPATH/bin/goveralls -service=travis-ci
script:
  - go build -i -o bin/ephemeral-roles ephemeral-roles.go
before_deploy:
  - zip -r ephemeral-roles.zip .
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  region: us-east-1
  access_key_id: AKIAJUUEKXMZKF4T6VHQ
  secret_access_key:
      secure: "PcU+5SosTLXSnWzwrxntqIMkUTjSnYmq2zdksT8QWUS51mexSpnA+hhe+59Q2yl68yNZoHhf4kPuZvyRGAqHsP1x6Y0aHaCMVN6Lnj7KYqPm2yh4MwvqUVgK76TbtpNZhCPsNE72QgAN5ojuHGGUgRYx5/cUHiynYNH5+FW6BtpCxSx1/7Zei/0kDZ3R4ZQcbFIX3tDgn0nq+Ih3yjhknQQA8RfDwXcbN3HCftWYZh/e1Niajnbwd5+u9ocW0Ckm+3LElj1q481kJWUZuCTnsCpQG9A8Uzto8UBNNlSaz+KaVEcjVp/eDqpuQtvKdfZNIuov8b7fUIWsoeL6HP5DxbqfqJ+hnwNNG4hwGWzbnuToNfqFOYkd5tQX5iPIGyhnunQHwQzVjJbcoiHpu8RIsWSC2y/CQLhetBj5CKh/YunDwKMSa48neeZeISoB6KgDwOZk9UcTUlubWBj1j95xNNOjLsbNsp90UbSCj69aECwwrTLtl5Aa6hsaJKr8BLVK6gugm8bj3C3mpO9K22XS0c6tb8/7MRlnpJPcAJcXyGfexl7g8LJ0h0rX4WtyvkiLa/JBvCXsGFuc+Y8d33VdZ2W2uHlfOQDl1UMRQNZ+ltBHAsPuzoPrfq2x+DplaiTs5NjZHX//sXyUuTkwgovTCBtFb3GHOiRrz7TuyNlzG44="
  zip_file: ephemeral-roles.zip
  app: ephemeral-roles
  env: ephemeral-roles
  bucket_name: ephemeral-roles
  wait-until-deployed: true
  on:
    repo: ewohltman/ephemeral-roles
    branch: master
