---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ephemeral-roles
  namespace: ephemeral-roles
  labels:
    app: ephemeral-roles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ephemeral-roles
  template:
    metadata:
      labels:
        app: ephemeral-roles
        version: "{COMMIT}"
    spec:
      containers:
        - name: ephemeral-roles
          image: ewohltman/ephemeral-roles:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: BOT_TOKEN
              value: "{BOT_TOKEN}"
            - name: DISCORDRUS_WEBHOOK_URL
              value: "{DISCORDRUS_WEBHOOK_URL}"
            - name: DISCORDBOTS_ORG_BOT_ID
              value: "{DISCORDBOTS_ORG_BOT_ID}"
            - name: DISCORDBOTS_ORG_TOKEN
              value: "{DISCORDBOTS_ORG_TOKEN}"
            - name: BOT_NAME
              value: "Ephemeral Roles"
            - name: BOT_KEYWORD
              value: "!eph"
            - name: ROLE_PREFIX
              value: "{eph}"
            - name: ROLE_COLOR_HEX2DEC
              value: "16753920"
            - name: LOG_TIMEZONE_LOCATION
              value: "America/New_York"
            - name: LOG_LEVEL
              value: "info"
          ports:
            - name: http
              containerPort: 8080
