apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ephemeral-roles
  namespace: ephemeral-roles
  labels:
    app: ephemeral-roles
  annotations:
    kubernetes.io/ingress.class: "contour"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ephemeral-roles
              servicePort: 80