---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: ephemeral-roles
spec:
  strategy: allinone
  allInOne:
    image: jaegertracing/all-in-one:1.17.0
    options:
      log-level: info
  storage:
    type: memory
    options:
      memory:
        max-traces: 100000
  ingress:
    enabled: false
