---
apiVersion: v1
kind: Service
metadata:
  name: ephemeral-roles
  namespace: ephemeral-roles
  labels:
    app: ephemeral-roles
spec:
  selector:
    app: ephemeral-roles
  ports:
    - name: http
      port: 8080
