apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ephemeral-roles
  namespace: ephemeral-roles
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: ephemeral-roles