---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ephemeral-roles
  namespace: ephemeral-roles
  labels:
    app: ephemeral-roles
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ephemeral-roles
  serviceName: ephemeral-roles
  template:
    metadata:
      labels:
        app: ephemeral-roles
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: ephemeral-roles
          image: ewohltman/ephemeral-roles:v1.16.2
          imagePullPolicy: Always
          env:
            - name: SHARD_COUNT
              value: "10"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_TIMEZONE_LOCATION
              value: "America/New_York"
            - name: INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ephemeral-roles
                  key: bot-token
            - name: DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: ephemeral-roles
                  key: discordrus-webhook-url
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 3
