---
name: pull_request_master
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Download dependencies
        run: make tidy

      - name: Run go vet
        run: make vet

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12.2

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build

      - name: Build Docker image
        run: make image

      - name: Push Docker image
        env:
          DOCKER_USER: "${{ secrets.DOCKER_USER }}"
          DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"
        run: make push
