---
name: pull_request_master
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          check-latest: true

      - name: Download dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run go vet
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55

      - name: Run tests
        run: make test

      - name: Run test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PATH="${PATH}:$(go env GOPATH)/bin"
          GO111MODULE=off go get -u github.com/mattn/goveralls
          goveralls -coverprofile=coverage.out -service=github

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Build binary
        run: make build

      - name: Build Docker image
        run: make image

      - name: Push Docker image
        env:
          DOCKER_USER: "${{ secrets.DOCKER_USER }}"
          DOCKER_PASS: "${{ secrets.DOCKER_PASS }}"
        run: make push
