---
name: pull_request
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true

      - name: Download dependencies
        run: make tidy

      - name: Run go vet
        run: make vet

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build

      - name: Build Docker image
        run: make image
