name: Push Branch Master
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go mod download

      - name: Run linters
        run: |
          PATH="${PATH}:$(go env GOPATH)/bin"
          INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh"

          curl -sSfL "${INSTALL_SCRIPT_URL}" | sh -s -- -b $(go env GOPATH)/bin v1.23.1

          make lint

      - name: Run tests
        run: make test

      - name: Build binary
        run: make build

      - name: Build Docker image
        run: make image

      - name: Push Docker image
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_USER }}
        run: make push

      - name: Deploy to Kubernetes
        env:
          KUBERNETES_CONFIG: ${{ secrets.KUBERNETES_CONFIG }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DISCORDRUS_WEBHOOK_URL: ${{ secrets.DISCORDRUS_WEBHOOK_URL }}
          DISCORDBOTS_ORG_BOT_ID: ${{ secrets.DISCORDBOTS_ORG_BOT_ID }}
          DISCORDBOTS_ORG_TOKEN:  ${{ secrets.DISCORDBOTS_ORG_TOKEN }}
        run: |
          PATH="${PATH}:$(go env GOPATH)/bin"
          KUBECTL_BIN="$(go env GOPATH)/bin/kubectl"

          KUBECTL_VERSION="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
          KUBECTL_URL="https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"

          mkdir ~/.kube
          echo "${KUBERNETES_CONFIG}" > ~/.kube/config

          curl -sL "${KUBECTL_URL}" -o "${KUBECTL_BIN}" && chmod +x "${KUBECTL_BIN}"

          make deploy
